meal/urls.py
from django.urls import path

from .views import home_view,modarator_view,MealCreateView,ProductCreateView,ProductListView,AddBalanceCreateView,add_balance_approve_view,ExpensesListView,add_expense_approve_view,generate_pdf_report

app_name = 'meal'

urlpatterns = [
    path('',home_view, name='home'),
    path('modarator/',modarator_view, name='modarator_view'),
    path('create/meal/',MealCreateView.as_view(), name='create'),
    path('expense/add/product/',ProductCreateView.as_view(), name='add_expense_product'),
    path('expense/product/list/',ProductListView.as_view(), name='expense_product_list'),
    path('expense/list/',ExpensesListView.as_view(), name='expense_list'),
    path('add/balance/',AddBalanceCreateView.as_view(), name='add_balance'),
    path('add/balance/<int:id>/approve/',add_balance_approve_view, name='add_balance_approve'),
    path('add/expense/<int:id>/approve/',add_expense_approve_view, name='add_expense_approve'),
    path('generate/pdf/report/',generate_pdf_report, name='generate_pdf_report'),
]

mealmanagement/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('meal.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

meal/models.py
from django.db import models
import datetime
from django.utils.timezone import localtime, now,localdate
from django.contrib.auth import get_user_model


class Meal(models.Model):
    meal_number     = models.IntegerField(verbose_name='meal number',default=0)
    guest_meal      = models.IntegerField(verbose_name='guest meal number',default=0)
    total_meal      = models.IntegerField(verbose_name='total meal number',default=0)
    date            = models.DateField(default=localdate())
    user            = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    class Meta:
        constraints = [
                models.UniqueConstraint(fields=['date', 'user'], name='user_unique_day_meal')
        ]

    def __str__(self):
        return str(self.date)

    def save(self, *args, **kwargs):
        self.total_meal = self.meal_number + self.guest_meal
        super().save(*args, **kwargs)  # Call the "real" save() method.


class Expenses(models.Model):
    amount          = models.IntegerField()
    date            = models.DateField(default=localdate(),null=True,blank=True)
    user            = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    approved        = models.BooleanField(default=False)

    class Meta:
        constraints = [
                models.UniqueConstraint(fields=['date', 'user'], name='user_unique_day_expense')
        ]
    def __str__(self):
        return '%s-%s' % (self.id, self.date)

class Product(models.Model):
    name          = models.CharField(verbose_name="product name",max_length=20)
    quantity      = models.IntegerField(help_text="quantity in kg/ltr",null=True,blank=True)
    amount        = models.IntegerField(help_text="amount in TK")
    date          = models.DateField(default=localdate())
    user          = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Balance(models.Model):
    amount          = models.IntegerField(default=0)
    user            = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,unique=True)

    def __str__(self):
        return '%s-%s' % (self.user, self.amount)


class AddBalance(models.Model):
    amount          = models.PositiveIntegerField()
    date            = models.DateField(default=localdate())
    user            = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    approved        = models.BooleanField(default=False)

    def __str__(self):
        return '%s-%s' % (self.date, self.amount)

meal/forms.py
from .models import Meal,Product,Expenses,AddBalance,Balance
from django import forms
import datetime
from django.forms import SelectDateWidget


class MealModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MealModelForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = Meal
        fields = ["meal_number","guest_meal","date"]
        widgets = {
            'date':SelectDateWidget(
        empty_label=("Choose Year", "Choose Month", "Choose Day"),
    ),
        }

class ProductModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProductModelForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = Product
        fields = ("name","quantity","amount","date",)
        widgets = {
            'date':SelectDateWidget(
        empty_label=("Choose Year", "Choose Month", "Choose Day"),
    ), 
    }

class BalanceModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BalanceModelForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Balance
        fields = ("amount",)

class AddBalanceModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AddBalanceModelForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = AddBalance
        fields = ("amount","date",)
        widgets = {
            'date':SelectDateWidget(
        empty_label=("Choose Year", "Choose Month", "Choose Day"),
    ), 
    }

meal/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import get_user_model
import datetime
import calendar
from django.utils.timezone import localtime, now,localdate
from .models import Meal,Product,Expenses,AddBalance,Balance
from django.db.models import Sum
from django.urls import reverse_lazy
from .forms import MealModelForm,ProductModelForm,BalanceModelForm,AddBalanceModelForm
from django.views.generic import CreateView,UpdateView,DeleteView,ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from .utility import render_to_pdf 

#@login_required
def home_view(request):
    # base query all model all data
    User = get_user_model()
    all_user = User.objects.all().order_by('date_joined')
    meal_list = Meal.objects.all().order_by('user__date_joined')
    product_list = Product.objects.all()
    expenses_list = Expenses.objects.all()
    add_balance_list = AddBalance.objects.all()
    all_user_balance = Balance.objects.all()

    # date and user related variable 
    user_count = len(all_user)
    user_id = list()
    user_dict = dict()
    for user in all_user:
        user_id.append(user.id)
        user_dict[user.id]=user.username
    # current date
    today = datetime.date.today()
    # month name
    today = str(today)
    year,month,day = today.split("-")
    year = int(year)
    month = int(month)
    day = int(day)
    month_name = calendar.month_name[month]
    # last day of month & day list of the month
    last_day = int(calendar.monthrange(year, month)[1])
    month_day_list=[i for i in range(1,last_day+1)] # test range func directly  

    # meal table data format 
    temp_dict = dict()
    for each in meal_list:
        if each.user.username not in temp_dict:
            temp_dict[each.user.username] = []
        temp_dict[each.user.username].append((each.date.day,each.total_meal))
    # create dummy data
    dummy_data_dict = dict()
    for day in month_day_list:
        if day not in dummy_data_dict:
            dummy_data_dict[day]=[]
            for __num in range(user_count):
                dummy_data_dict[day].append(0)
    # update dummy data with db value
    count = 0
    for key in temp_dict.keys():
        values = temp_dict[key]
        for date_value in values:
                if date_value[0] in dummy_data_dict.keys():
                    actual_meal_data = dummy_data_dict[date_value[0]]
                    actual_meal_data[count] = date_value[1]
        count += 1

    # formated data as dictionary
    final_data = dummy_data_dict

    # user balance
    user_balance_object,created = Balance.objects.get_or_create(user=request.user)
    print(user_balance_object,created)
    user_balance = user_balance_object.amount
    # user balance add request
    user_added_balance= add_balance_list.filter(user=request.user,approved=True).aggregate(Sum('amount'))
    if user_added_balance['amount__sum'] is None:
        user_added_balance['amount__sum'] = 0
    user_added_balance = int(user_added_balance['amount__sum'])
    # user expenses
    user_expenses = Expenses.objects.filter(user=request.user,approved=True).aggregate(Sum('amount'))
    if user_expenses['amount__sum'] is None:
        user_expenses['amount__sum']=0
    user_expenses = int(user_expenses['amount__sum'])
    # each user total meal
    user_meal_for_month = Meal.objects.filter(user=request.user).aggregate(Sum('total_meal'))
    if user_meal_for_month['total_meal__sum'] is None:
        user_meal_for_month['total_meal__sum']=0
    user_meal_for_month = int(user_meal_for_month['total_meal__sum'])
    # all user total meal
    all_user_meal_for_month = Meal.objects.all().aggregate(Sum('total_meal'))
    if all_user_meal_for_month['total_meal__sum'] is None:
        all_user_meal_for_month['total_meal__sum']=0
    all_user_meal_for_month = int(all_user_meal_for_month['total_meal__sum'])
    # all user add balance total
    all_user_added_balance= AddBalance.objects.filter(approved=True).aggregate(Sum('amount'))
    if all_user_added_balance['amount__sum'] is None:
        all_user_added_balance['amount__sum'] = 0
    all_user_added_balance = int(all_user_added_balance['amount__sum'])
    # all user expenses
    all_user_expenses = Expenses.objects.filter(approved=True).aggregate(Sum('amount'))
    if all_user_expenses['amount__sum'] is None:
        all_user_expenses['amount__sum']=0
    all_user_expenses = int(all_user_expenses['amount__sum'])
    # meal rate
    if all_user_meal_for_month == 0:
        meal_rate = 0
    else:
        meal_rate = round((all_user_expenses/all_user_meal_for_month),2)
    # Total Balance
    total_balance = all_user_added_balance - all_user_expenses
    # user actual balance
    user_actual_balance = (user_added_balance + user_expenses) - round((user_meal_for_month*meal_rate))

    context={
        "all_user":all_user,
        "current_year":year,
        "current_month_number":month,
        "current_month_name":month_name,
        "current_day":day,
        "last_day_of_the_month":last_day,
        "month_day_list":month_day_list,
        "data":final_data,
        "user_balance":user_actual_balance,
        "user_added_balance":user_added_balance,
        "user_expenses":user_expenses,
        "user_total_meal":user_meal_for_month,
        "total_meal":all_user_meal_for_month,
        "total_received":all_user_added_balance,
        "total_expenses":all_user_expenses,
        "meal_rate":meal_rate,
        "total_balance":total_balance,

    }

    return render(request,'meal/home.html',context=context)

class MealCreateView(CreateView):
    model = Meal
    form_class = MealModelForm
    template_name = 'meal/create.html'
    success_url = reverse_lazy('meal:home')

    def form_valid(self,form):
        if self.request.user.is_authenticated:
            form.instance.user = self.request.user
        return super().form_valid(form)

class ProductListView(LoginRequiredMixin,ListView):
    model = Product
    template_name = 'meal/add_product_list.html'
    context_object_name = 'products'

    def get_queryset(self):
        super().get_queryset()
        queryset = Product.objects.filter(user=self.request.user).order_by('date')
        return queryset


class ExpensesListView(ListView):
    model = Expenses
    context_object_name = 'expenses_list'
    template_name = 'meal/expense_list.html'

class ProductCreateView(CreateView):
    model = Product
    template_name = 'meal/add_product.html'
    success_url = reverse_lazy('meal:expense_list')
    form_class = ProductModelForm

    def form_valid(self,form):
        if self.request.user.is_authenticated:
            form.instance.user = self.request.user
            self.object = form.save()
            print(self.object.date)
            get_expense_model_data,created = Expenses.objects.get_or_create(user=self.request.user,date=self.object.date,defaults={'amount':0})
            if created is True:
                get_expense_model_data.amount=self.object.amount
                get_expense_model_data.save()
            else:
                get_expense_model_data = Expenses.objects.get(user=self.request.user,date=self.object.date)
                get_expense_model_data.amount += self.object.amount
                get_expense_model_data.save()
        response = super(ProductCreateView, self).form_valid(form)
        return response


class AddBalanceCreateView(CreateView):
    model = AddBalance
    template_name = 'meal/add_balance.html'
    success_url = reverse_lazy('meal:home')
    form_class = AddBalanceModelForm

    def form_valid(self,form):
        if self.request.user.is_authenticated:
            form.instance.user = self.request.user
        return super(AddBalanceCreateView,self).form_valid(form)


def modarator_view(request):
    add_balance_not_approved = AddBalance.objects.filter(approved=False)
    add_expense_not_approved = Expenses.objects.filter(approved=False)
    context={
        'add_balance_not_approved':add_balance_not_approved,
        'add_expense_not_approved':add_expense_not_approved,
    }
    return render(request,'meal/modarator.html',context=context)

def add_balance_approve_view(request,id):
    data = AddBalance.objects.get(id=id)
    data.approved = True
    x,created = Balance.objects.get_or_create(user=data.user)
    x.amount +=  data.amount
    data.save()
    x.save()
    return redirect(reverse_lazy('meal:modarator_view'))

def add_expense_approve_view(request,id):
    data = Expenses.objects.get(id=id)
    data.approved = True
    x,created = Balance.objects.get_or_create(user=data.user)
    x.amount +=  data.amount
    data.save()
    x.save()
    return redirect(reverse_lazy('meal:modarator_view'))


# pdf generate 

def generate_pdf_report(request):
    # base query all model all data
    User = get_user_model()
    all_user = User.objects.all().order_by('date_joined')
    meal_list = Meal.objects.all().order_by('user__date_joined')
    product_list = Product.objects.all()
    expenses_list = Expenses.objects.all()
    add_balance_list = AddBalance.objects.all()
    all_user_balance = Balance.objects.all()

    # date and user related variable 
    # current date
    today = datetime.date.today()
    # report generated time
    report_generated_time = datetime.datetime.now().strftime('%I:%M:%S %p')
    # month name
    today = str(today)
    year,month,day = today.split("-")
    year = int(year)
    month = int(month)
    day = int(day)
    month_name = calendar.month_name[month]
    # last day of month & day list of the month
    last_day = int(calendar.monthrange(year, month)[1])

    # user balance
    user_balance_object,created = Balance.objects.get_or_create(user=request.user)
    user_balance = user_balance_object.amount
    # user balance add request

templates/meal/add_balance.html
{% extends 'base.html' %}

{% block content %}

  <div class="row d-flex justify-content-center">
    <div class="col-6 mt-5">
      <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-danger col-12" type="submit" value="Add Balance">
      </form>
    </div>
  </div>
{% endblock content %}

templates/meal/add_product.html
{% extends 'base.html' %}

{% block content %}
  <div class="row d-flex justify-content-center">
    <div class="col-6 mt-5">
      <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-danger col-12" type="submit" value="Add Expense">
      </form>
    </div>
  </div>
{% endblock content %}

templates/meal/add_product_list.html
{% extends 'base.html' %}

{% block content %}

  <div class="row mt-5 d-flex justify-content-center">
    {% for product in products %}
      <div class="col">
        <div class="card text-white bg-success  text-center mb-3" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">{{product.date}}</h5>
            <h1 class="display-3">{{product.amount}}</h1>
            <h5 class="card-title">{{product.name}}</h5>
            <div class="card-footer">
              <a href="#" class="card-link text-center text-white">edit</a>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

  <div>
    <a class="btn btn-lg btn-danger" href="{% url 'meal:add_expense_product'%}" style="position:fixed;bottom:20px;right:45px;margin:0;padding:5px 3px;">Add Expense</a>
  </div>

{% endblock content %}

templates/meal/create.html
{% extends 'base.html' %}

{% block content %}
  <div class="mt-5">
    <form action="" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="create">
    </form>
  </div>
{% endblock content %}

templates/meal/expense_list.html
{% extends 'base.html' %}

{% block content %}

  <div class="row mt-5 d-flex justify-content-center">
    {% for expense in expenses_list %}
      <div class="col">
        <div class="card text-white bg-success  text-center mb-3" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">{{expense.date}}</h5>
            <h1 class="display-3">{{expense.amount}}</h1>
            <div class="card-footer">
              {% if expense.approved is True %}
                <span class="text-center text-white">Approved</span>
              {% else %}
                <span class="text-center text-white">Not Approved</span>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

  <div>
    <a class="btn btn-lg btn-danger" href="{% url 'meal:add_expense_product'%}" style="position:fixed;bottom:20px;right:45px;margin:0;padding:5px 3px;">Add Bazar</a>
  </div>

{% endblock content %}

templates/meal/home.html
{% extends 'base.html' %}

{% block content %}
  <div class='container mt-5 mb-5'>

    <div class="row mt-3 d-flex justify-content-center">
      <div class="col">
        <div class="card text-white bg-success  text-center mb-3" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">TOTAL ADDED</h5>
            {% if user_added_balance %}
              <h1 class="display-3">{{user_added_balance}}</h1>
            {% else %}
              <h1 class="display-3">0</h1>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card text-white bg-success  text-center mb-3" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">EXPENSE</h5>
            {% if user_expenses %}
              <h1 class="display-3">{{user_expenses}}</h1>
            {% else %}
              <h1 class="display-3">0</h1>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card text-white bg-success  text-center mb-3" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">BALANCE</h5>
            {% if user_balance %}
              <h1 class="display-3">{{user_balance}}</h1>
            {% else %}
              <h1 class="display-3">0</h1>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

    <div class="row mt-5 mb-5 d-flex justify-content-center">
      <div class="col">
        <table class="table table-info table-striped table-bordered text-center">
          <thead>
            <tr>
              <th scope="col" colspan="12">Meal table for
                {{current_month_name}}
                -
                {{current_year}}
              </th>
            </tr>
            <tr>
              <th scope="col">Date</th>
              {% for user in all_user %}
                <th scope="col">{{user.username}}</th>
              {% endfor %}
            </tr>
          </thead>
          <tbody>
            {% for key, values in data.items %}
              <tr>
                <th scope="row">{{key}}</th>
                {% for val in values %}
                  <td>{{val}}</td>
                {% endfor %}
              </tr>
            {% endfor %}
          </tbody>
        </table>

      </div>
    </div>

    <div class="row mt-3 d-flex justify-content-center ">
      <div class="col">
        <div class="card text-white bg-success  text-center mb-3" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">MEAL</h5>
            {% if user_total_meal %}
              <h1 class="display-3">{{user_total_meal}}</h1>
            {% else %}
              <h1 class="display-3">0</h1>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card text-white bg-success  text-center mb-3" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">TOTAL MEAL</h5>
            {% if total_meal %}
              <h1 class="display-3">{{total_meal}}</h1>
            {% else %}
              <h1 class="display-3">0</h1>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card text-white bg-success  text-center mb-3" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">MEAL RATE</h5>
            {% if meal_rate %}
              <h1 class="display-3">{{meal_rate}}</h1>
            {% else %}
              <h5>something missing contact admin.</h5>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

    <div class="row mt-3 d-flex justify-content-center">
      <div class="col">
        <div class="card text-white bg-success  text-center mb-3" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">TOTAL RECEIVED</h5>
            {% if total_received %}
              <h1 class="display-3">{{total_received}}</h1>
            {% else %}
              <h1 class="display-3">0</h1>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card text-white bg-success  text-center mb-3" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">TOTAL EXPENSE</h5>
            {% if total_expenses %}
              <h1 class="display-3">{{total_expenses}}</h1>
            {% else %}
              <h1 class="display-3">0</h1>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card text-white bg-success  text-center mb-3" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">TOTAL BALANCE</h5>
            {% if total_balance %}
              <h1 class="display-3">{{total_balance}}</h1>
            {% else %}
              <h5>something missing contact admin.</h5>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

    <div class="d-grid gap-2">
      <button class="btn btn-lg btn-primary" type="button" onclick="location.href='{% url "meal:generate_pdf_report"%}'">Generate Report</button>
    </div>

  </div>
  <div class="mb-5"></div>
</div>
<div class="mb-5"></div>
{% endblock content %}

templates/meal/modarator.html
{% extends 'base.html' %}

{% block content %}
  <div class="row mt-5 d-flex justify-content-center">
    <div class="col-8">
      <h1 class="display-5 text-center mb-5">Request For Approve Add Balance</h1>
      {% if add_balance_not_approved %}
        {% for each in add_balance_not_approved %}
          <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between ">
              <div>
                {{each.amount}}
                Tk - by
                {{each.user.username}}
                on
                {{each.date}}
              </div>
              <div>
                <button type="submit" class="btn btn-danger" onclick="location.href='{% url 'meal:add_balance_approve' each.id %}'" value="Approve">Approve
                </div>
              </li>
            </ul>
          {% endfor %}
        {% else %}
          <h1 class="display-4 text-center ">No request yet.</h1>
          <div class="text-center">
            <button type="submit" class="btn btn-danger col-4" onclick="location.href='{% url 'meal:add_balance' %}'">
              Add Money Request</button>
          </div>
        {% endif %}
      </div>
    </div>

    <div class="row mt-5 d-flex justify-content-center">
      <div class="col-8">
        <h1 class="display-5 text-center mb-5">Request For Approve Expenses
        </h1>
        {% if add_expense_not_approved %}
          {% for each in add_expense_not_approved %}
            <ul class="list-group">
              <li class="list-group-item d-flex justify-content-between ">
                <div>
                  {{each.amount}}
                  Tk - by
                  {{each.user.username}}
                  on
                  {{each.date}}
                </div>
                <div>
                  <button type="submit" class="btn btn-danger" onclick="location.href='{% url 'meal:add_expense_approve' each.id %}'" value="Approve">Approve
                  </div>
                </li>
              </ul>
            {% endfor %}
          {% else %}
            <h1 class="display-4 text-center ">No request yet.</h1>
            <div class="text-center">
              <button type="submit" class="btn btn-danger col-4" onclick="location.href='{% url 'meal:add_expense_product' %}'">
                Add expense Request</button>
            </div>
          {% endif %}
        </div>
      </div>
    {% endblock content %}

templates/meal/table.html
<h2 class='m-5'>table
</h2>
<div class='container mb-5'>

  <table class="table table-striped table-bordered text-center">
    <thead>
      <tr>
        <th scope="col" colspan="5">Meal table for March
        </th>
      </tr>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">rashedi</th>
        <th scope="col">rahul</th>
        <th scope="col">bappy</th>
        <th scope="col">rifat</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">2022-03-1</th>
        <td>2</td>
        <td>2</td>
        <td>2</td>
        <td>2</td>
      </tr>
      <tr>
        <th scope="row">2022-03-2</th>
        <td>2</td>
        <td>2</td>
        <td>2</td>
        <td>2</td>
      </tr>
      <tr>
        <th scope="row">2022-03-3</th>
        <td>2</td>
        <td>2</td>
        <td>2</td>
        <td>2</td>
      </tr>
      <tr>
        <th scope="row">2022-03-4</th>
        <td>2</td>
        <td>2</td>
        <td>2</td>
        <td>2</td>
      </tr>
    </tbody>
  </table>

</div>

templates/meal/user_report.html
<!DOCTYPE>
<html>

  <head>
    <title>Title</title>
    <style type="text/css">
      body {
        font-weight: 200;
        font-size: 14px;
      }

      .header {
        font-size: 20px;
        font-weight: 100;
        text-align: center;
        color: #007cae;
      }

      .title {
        font-size: 22px;
        font-weight: 100;
        /* text-align: right;*/
        padding: 10px 20px 0;
      }

      .title span {
        color: #007cae;
      }

      .details {
        padding: 10px 20px 0;
        text-align: left !important;
        /*margin-left: 40%;*/
      }

      .hrItem {
        border: none;
        height: 1px;
        /* Set the hr color */
        color: #333;
        /* old IE */
        background-color: #fff;
        /* Modern Browsers */
      }
    </style>
  </head>

  <body>
    <div class='wrapper'>
      <div class='header'>
        <p class='title'>Meal report for
          {{month_name}}-{{year}}
        </p>
      </div>
      <div>
        <div class='details'>
          Report For:
          {{user_name}}<br/>
          Date:
          {{report_generated_date}}<br/>
          Time:
          {{report_generated_time}}<br/>
          Last Day Of
          {{month_name}}
          :
          {{last_day}}
          <hr class='hrItem'/>
        </div>
        <div class="details">
          user_added_balance :
          {{user_added_balance}}<br/>
          user_expenses :
          {{user_expenses}}<br/>
          user_meal :
          {{user_meal}}<br/>
          meal_rate :
          {{meal_rate}}<br/>
          user_actual_balance :
          {{user_actual_balance}}<br/>
        </div>
      </div>
    </body>

  </html>