meal/urls.py
from django.urls import path

from .views import home_view,modarator_view,MealCreateView,ProductCreateView,ProductListView,AddBalanceCreateView,add_balance_approve_view,ExpensesListView,add_expense_approve_view,generate_pdf_report

app_name = 'meal'

urlpatterns = [
    path('',home_view, name='home'),
    path('modarator/',modarator_view, name='modarator_view'),
    path('create/meal/',MealCreateView.as_view(), name='create'),
    path('expense/add/product/',ProductCreateView.as_view(), name='add_expense_product'),
    path('expense/product/list/',ProductListView.as_view(), name='expense_product_list'),
    path('expense/list/',ExpensesListView.as_view(), name='expense_list'),
    path('add/balance/',AddBalanceCreateView.as_view(), name='add_balance'),
    path('add/balance/<int:id>/approve/',add_balance_approve_view, name='add_balance_approve'),
    path('add/expense/<int:id>/approve/',add_expense_approve_view, name='add_expense_approve'),
    path('generate/pdf/report/',generate_pdf_report, name='generate_pdf_report'),
]

mealmanagement/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('meal.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

templates/base.html
<!doctype html>
<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {% block title %}
      <title>Meal - management system</title>
    {% endblock title %}
  </head>

  <body>

    {% include 'nav.html' %}
    <div class="container">
      {% block content %}{% endblock content %}
    </div>
    {% include 'footer.html' %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>

</html>

templates/footer.html
<footer class="footer py-3 bg-dark text-white fixed-bottom">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col text-center">
        <h6>&copy;Md. Mobassher Rashedi</h6>
      </div>
    </div>
  </div>
</footer>

templates/nav.html
<!-- templates/navbar.html -->
<nav class="navbar navbar-expand-md sticky-top navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'meal:home' %}">Meal App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-row-reverse" id="navbarTogglerDemo02">
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
          {% if user.is_staff %}
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'meal:modarator_view' %}">View request</a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'meal:create' %}">Add a meal</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'meal:add_expense_product' %}">Add a expense</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'meal:add_balance' %}">Add balance request</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" href="#">Hi
              {{user.username}}</a>
          </li>
        {% else %}

          <li class="nav-item">
            <a href="{% url 'login' %}" class="btn btn-sm btn-danger">Sign In</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>